### ISSUE TITLE
Disable preset modes by configuration

### ISSUE THREAD

**Issue by llleonzhao** [syssi/xiaomi_fan#121]
How can I turn off the initial four gears, I found that it is not very friendly to use in homekit, and the switch is not very effective every time.

**Comment by syssi** [comment]
Could you test this feature branch? Does it work for you?

```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.130.71
    override_preset_modes: []
```

https://github.com/syssi/xiaomi_fan/archive/refs/heads/feature/override-preset-modes-by-configuration.zip
