### ISSUE TITLE
Natural speed Homekit switch

### ISSUE THREAD

**Issue by kristofferR** [syssi/xiaomi_fan#137]
Thanks for the great plugin, got my new Xiaomi Pedestal 2S fan set up in HA/HomeKit in no time with it.  

However, I really like the natural mode of the fan, and would like to switch between it and constant speed using a HomeKit switch(like the presets I disabled were).

How do I create such a switch, so I can toggle Natural mode through HomeKit/Siri? I'd still like to use the speed slider.

**Comment by TDK2525** [comment]
Id love to figure this out too!

**Comment by damianpasek** [comment]
Here is the solution which I'm using, custom switch using template. Later on you can expose the switch to Homekit. Maybe this will help you 🙂
```
- platform: template
  switches:
    bedroom_fan_natural:
      friendly_name: "Bedroom Fan Natural Mode"
      icon_template: mdi:weather-windy
      value_template: >- 
        {{ state_attr('fan.bedroom_fan', 'natural_speed')|int > 0 }}
      turn_on:
        service: xiaomi_miio_fan.fan_set_natural_mode_on
        data:
          entity_id: fan.bedroom_fan
      turn_off:
        service: xiaomi_miio_fan.fan_set_natural_mode_off
        data:
          entity_id: fan.bedroom_fan
```
