### ISSUE TITLE
Support device model zhimi.fan.sa1

### ISSUE THREAD

**Issue by zhumuht** [syssi/xiaomi_fan#15]
Update for fan.xiaomi_smart_fan fails
下午9:48 custom_components/fan/xiaomi_miio_fan.py (ERROR)
unable to parse json '{"result":[null,null,120,468,0,"on","on",null,"on",100,74,"off",2get_down],"id":515}': Expecting ',' delimiter: line 1 column 66 (char 65)
下午9:48 /srv/homeassistant/lib64/python3.6/site-packages/miio/protocol.py (ERROR)
```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: xxx.xxx.xxx.xx
    token: xxxxxxxxxxxxxxxxxxxxx
    model: zhimi.fan.v3
```

if not set model, log is:
```
Log Details (ERROR)
Sat Jun 23 2018 23:24:26 GMT+0800 (CST)

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues 
and provide the following data: zhimi.fan.sa1
```
