### ISSUE TITLE
dmaker.fan.p15 unavailable

### ISSUE THREAD

**Issue by cirolaferrara** [syssi/xiaomi_fan#188]
My conf
```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.1.77
    token: xxxxxxxxxx
    model: dmaker.fan.p15
```

Firmware: 2.0.7.005
HA: 2022.5.5
xiaomi_fan: 2022.4.0.0
