### ISSUE TITLE
adding multiple fans failing in home assistant

### ISSUE THREAD

**Issue by AdamBremholm** [syssi/xiaomi_fan#192]
I am trying to add multiple fans but I am getting an error when adding the second one in confiuration.yaml and restarting home assistant. If i just put the first one I can restart fine. Am i doing something wrong in the configuration?

"Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Platform error fan.xiaomi_miio-fan - Integration 'xiaomi_miio-fan' not found."

This is the configuration:

```
fan:
  - platform: xiaomi_miio_fan
    name: sovrumsfläkt
    model: zhimi.fan.za5
    host: xxxx
    token: xxxxx
  - platform: xiaomi_miio-fan
    name: barnrumsfläkt
    model: zhimi.fan.za5
    host: xxxx
    token: xxxxx
```
