### ISSUE TITLE
Mi Standing Fan 2 (dmaker.fan.p18) not being discovered

### ISSUE THREAD

**Issue by mariocao** [syssi/xiaomi_fan#198]
Hi,

I just bought a new Mi Standing Fan 2 (`dmaker.fan.p18`, model `BPLDS02DM`) and it seems the integration cannot connect to it. I double-checked that the IP is reachable from HA and this is the only log I get:

```
2022-07-22 21:02:50 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.107.23; Retrying in background in 30 seconds
```

The current fan firmware is 2.0.7.0003 (I did not upgrade it...).

If in my config, I specify the `model` field, I don't get any error at all but the created entity is `unavailable` all the time. :/

```yaml
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.107.23
    token: <TOKEN>
    model: dmaker.fan.p18
```

Thanks in advance for any idea about what could be happening and, obviously, for all the work in the integration! :clap:
