### ISSUE TITLE
fan.xiaomi_miio_set_oscillation_angle not working

### ISSUE THREAD

**Issue by jacekpaszkowski** [syssi/xiaomi_fan#2]
Hi,

could you please check if fan.xiaomi_miio_set_oscillation_angle sevice is working? I have problem in my setup. Calling service does nothing, even there is no info in logs :(
I'm using other services like fan.xiaomi_miio_set_natural_mode_on with no issue.

Regards,
Jacek

**Comment by syssi** [comment]
Pleae enable the debug log and provide some more details of your home-assistant.log.

```
# configuration.yaml

logger:                                                                                                                                                                                                                                        
  default: warn                                                                                                                                                                                                                                
  logs:                                                                                                                                                                                                                                        
    custom_components.fan.xiaomi_miio_fan: debug                                                                                                                                                                                               
    miio: debug 
```

What's the response of the fan if you try to set the oscillation angle?
