### ISSUE TITLE
Mi Standing Fan 2 (dmaker.fan.p18) some configuration properties are missing

### ISSUE THREAD

**Issue by oOWaXOo** [syssi/xiaomi_fan#200]
I added the fan succesfully to my Home Assistant instance. But i'm missing some functions that were succesfully tested by @pooyashahidi  here  [comment](https://github.com/syssi/xiaomi_fan/pull/144#issuecomment-864562103) before.

I tried the config part **with**:
```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.xxx.xxx
    token: <token>
```

And **without** "model"
```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.xxx.xxx
    token: <token>
    model: dmaker.fan.p18
```

**What is actually working:**
![image](https://user-images.githubusercontent.com/47377832/181821179-87d34552-56da-4bfc-bcde-c0a6d046bd61.png)

**Actually missing:**

- [ ] - preselectable oscillation angles (30° ... 140°)
- [ ] - mode (straight / nature)
- [ ] - off delay timer (0min ... 480min)
- [ ] - child lock
- [ ] - buzzer
- [ ] - (turning the indicator LED on and off) didn't worked before.

Do you have any idea where this issue came from? Maybe something wrong with my configuration...

**Comment by pooyashahidi** [comment]
I call it from the UI like this:

```yaml
action: call-service
service: fan.set_direction
service_data:
  direction: forward
  entity_id: fan.xiaomi_smart_fan_2
```
