### ISSUE TITLE
dmaker.fan.p18 angle and timer

### ISSUE THREAD

**Issue by erbarto** [syssi/xiaomi_fan#201]
Hi!
I cannot setup the angle and timer in the frontend card.
These are the attrubutes of my fan:

preset_modes:
  - 'off'
  - Level 1
  - Level 2
  - Level 3
  - Level 4
direction: null
oscillating: true
percentage: 75
percentage_step: 1
preset_mode: Level 3
model: dmaker.fan.p18
angle: 60
raw_speed: 75
delay_off_countdown: 0
ac_power: null
oscillate: true
direct_speed: null
natural_speed: null
child_lock: false
buzzer: true
led_brightness: null
use_time: null
temperature: null
humidity: null
battery: null
battery_charge: null
button_pressed: null
led: false
battery_state: null
mode: normal
friendly_name: Xiaomi Smart Fan
supported_features: 15

**Comment by pooyashahidi** [comment]
You can use the "Developer Tools" in HA to familiarize yourself. Every service has example data that show how to call it.

For example,angle:
```yaml
service: xiaomi_miio_fan.fan_set_oscillation_angle
service_data:
  entity_id: fan.xiaomi_smart_fan_2
  angle: 60 # 60 degrees
```
Or Timer:
```yaml
service: xiaomi_miio_fan.fan_set_delay_off
service_data:
  entity_id: fan.xiaomi_smart_fan_2
  delay_off_countdown: 1 # will turn off in 1 minutes
```
Both work fine with p18
