### ISSUE TITLE
dmaker.fan.p220 not support

### ISSUE THREAD

**Issue by sstu** [syssi/xiaomi_fan#203]
Hi !
I tried add to configuration.yaml 

```
fan:
   - platform: xiaomi_miio_fan
     name: Xiaomi Mi Smart Standing Fan
     host: 192.168.0.28
     token: <token>
```

and in log:
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p220
