### ISSUE TITLE
Smartmi Standing Fan 2S, correct model no? Some things are not working.

### ISSUE THREAD

**Issue by benovic** [syssi/xiaomi_fan#220]
Hardware:
Name: Smartmi Standing Fan 2S
Model: ZLBPLDS03ZM

HA Configuration.yaml
```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: !secret fan_host
    token: !secret fan_token
```

Discovered as: zhimi.fan.za4

Problems, with the following using :
`default/fan_set_child_lock_on. Service not found.
`
`default/fan_set_oscillation_angle. Service not found.
`
`Fehler beim Aufrufen des Diensts fan/set_preset_mode. 'Nature'
`

maybe those are not supported (anymore) for my fan? 
maybe i have to override the model, but to what? It is not in the List, alas.
