### ISSUE TITLE
dmaker.fan.p39

### ISSUE THREAD

**Issue by Syngor** [syssi/xiaomi_fan#226]
I added the following code to my configuration.yaml:

```
fan:
  - platform: xiaomi_miio_fan
    name: My Fan
    host: 192.168.30.5
    token: my-token-here
    model: dmaker.fan.p39
```

I extracted the token using the token extractor: https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor. This token extractor also tells me it is a dmaker.fan.p39.

But my device remains 'unavailable'. I had to add the model to make it appear, without the model specified, it doesn't appear.
