### ISSUE TITLE
Fan not showing in HA

### ISSUE THREAD

**Issue by mazoku11** [syssi/xiaomi_fan#252]
Hi All,

I hope you could help me.

After following all steps, I am still not able to see my Mi Smart Fan 2 in HA (dmaker.fan.p18).

I am running my HA in a container (2024.4.4).

Token, IP and Model were obtained from the [Get MiHome devices token](https://github.com/Maxmudjon/Get_MiHome_devices_token/releases).

Installed HACS - working correctly
Installed this Xiaomi Mi Smart Pedestal Fan Integration - working correctly
Added the required "fan" entry in \homeassistant\config\configuration.yaml - not working

Copy of the entire configuration.yaml file:

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Load Xiaomi fan
fan:
  - platform: xiaomi_miio_fan
    name: Mi Smart Fan
    host: 192.168.100.182
    token: 37f5602f55a02411303071ed06d43456
    model: dmaker.fan.p18
```

After each step I did a restart of HA, as instructed.
The folder structure is there for HACS and this integration.
I tried adding and removing the entry in the configuration.yaml file and still nothing is showing in Devices & Services after restarts.

I tried re-downloading all of the HACS and Xiaomi Mi Smart Pedestal Fan Integration, but it did not help.

Regards,
M
