### ISSUE TITLE
dmaker.fan.p18 not being discovered

### ISSUE THREAD

**Issue by ministryofsillywalks** [syssi/xiaomi_fan#275]
I just bought a dmaker.fan.p18 and tried to add it via this component:
It's on the same network as my ha instance with no firewalls currently applied.
According to the xiaomi app the versions are:
MCU-FIrmware-Version: 0003
SDK-Firmware-Version: 2.1.3

![image](https://github.com/user-attachments/assets/b6bd6066-da0f-4fbf-bfac-7ba6b02792db)

I added the fan via the config as follows:
```

fan:
  - platform: xiaomi_miio_fan
    name: Schlafzimmer Ventilator
    host: 10.10.10.78
    token: XXX
```

I also tried adding it with the model. However both times home assistant throws an error:
![image](https://github.com/user-attachments/assets/3362ed54-9f72-495b-a6d4-6e3a93e2e588)

the device shows up however with the info "not available:
![image](https://github.com/user-attachments/assets/44b3a015-91f3-4ab4-94e4-71ef0cd72f77)

Any idea whats going on and what I could try to make the device available?
