### ISSUE TITLE
Automation not working

### ISSUE THREAD

**Issue by davidbenucci** [syssi/xiaomi_fan#287]
I installed the component on HAssio.
Home Assistant OS
Core: 2025.6.3
Supervisor: 2025.06.2
Operating System: 15.2
Frontend: 20250531.4

After reboot I have a new entity named MyFan (even if I cannot set via gui).
This is my configuration.yaml section:
```yaml
fan:
  - platform: xiaomi_miio_fan
    name: "MyFan"
    host: 192.168.0.133
    model: "dmaker.fan.p33"
    token: "03993a321470daac090aab3998502af9"
```
I created an automation to toggle the fan and set natural mode to off but it's not workin. The automation is activated ( Isaw it in "Traces") but the fan is off. Why? This is the automation code.

```yaml
id: '1750867969474'
alias: Test Ventilatore`
description: ''
triggers:
  - event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.pulsante_monitor_studio
      click_type: long_click_press
    trigger: event
conditions: []
actions:
  - action: fan.toggle
    metadata: {}
    data: {}
    target:
      entity_id: fan.myfan
  - action: xiaomi_miio_fan.fan_set_natural_mode_off
    metadata: {}
    data:
      entity_id: fan.myfan
mode: single`
