### ISSUE TITLE
Automation Issue

### ISSUE THREAD

**Issue by 18605000242** [syssi/xiaomi_fan#54]
I try to set my fan in a specific value every time turn on it.
But it only works with turn on/off. Hard to find a template to reference.
Hope someone can help to figure out. Many thanks.

```
action:
    - service: switch.turn_on
      entity_id: switch.plug_158d00032d5caa
    - service: fan.turn_on
      entity_id: fan.xiaomi_smart_fan
    - service: fan.set_speed
      data_template:
        entity_id: fan.xiaomi_smart_fan
        speed: 'level 1'
    - service: fan.oscillate
      data_template:
        eneity_id: fan.xiaomi_samrt_fan
        oscillating: 'true'
    - service: fan.xiaomi_miio_set_oscillation_angle
      data_template:
        entity_id: fan.xiaomi_smart_fan
        angle: '60'
```
