### ISSUE TITLE
Update of fan.XXX is taking over 10 seconds

### ISSUE THREAD

**Issue by HammerNL89** [syssi/xiaomi_fan#67]
Since a week I own a Smartmi Fan 2 (zhimi.fan.za3). I noticed this integration, and added it to my HA setup. All working fine, however, my log shows the following warning: 

`WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.ventilator is taking over 10 seconds`

In the last 24hrs this warning occurred ~30 times. I'm not experiencing any input problems when i want to control the device, however it's bit annoying that your logs is 'flooded' with the same warning. 

The room where the fan is placed, has a access point, and the fan is basically right next to it.

**Comment by mpepping** [comment]
Try enabling debug logging for clues:

```
logger:
  logs:
    custom_components.xiaomi_miio_fan: debug
    miio.miioprotocol: debug

```
