### ISSUE TITLE
fan.xiaomi_miio_set_led_brightness doesn't work

### ISSUE THREAD

**Issue by jacekpaszkowski** [syssi/xiaomi_fan#8]
Im' running latest version of component, when i invoke fan.xiaomi_miio_set_led_brightness nothing happens. "led_brightness" value doesn't change and no messages in log

**Comment by syssi** [comment]
Which version (model) of the fan do you have?

**Comment by jacekpaszkowski** [comment]
model: zhimi.fan.v3

**Comment by syssi** [comment]
Please enable the debug log:

```
# configuration.yaml
logger:
  default: warn
  logs:
    custom_components.fan.xiaomi_miio_fan: debug
    miio: debug
```

Restarte HA, toggle the different LED brightness values and provide the content of your home-assistant.log. It should contain the communication with the device (all requests & responses).
